create database jogo;
use jogo;

CREATE TABLE perguntas (
    pergunta	VARCHAR(512),
    alt1	VARCHAR(512),
    alt2	VARCHAR(512),
    alt3	VARCHAR(512),
    alt4	VARCHAR(512),
    resposta	int(1),
    materia	VARCHAR(512)
);

INSERT INTO perguntas (pergunta, alt1, alt2, alt3, alt4, resposta, materia) VALUES
	('Qual é a forma correta de comentar uma linha de código em Python? ', '// Comentário', '/* Comentário */', '# Comentário', '<!-- Comentário -->', '3', 'python'),
	('Qual dos seguintes tipos de dados em Python é imutável? ', 'List', 'Tuple', 'Set', 'Dictionary', '2', 'python'),
	('Qual função é usada para obter o comprimento de uma lista', 'count()', 'length()', 'size()', 'len()', '4', 'python'),
	('Qual é o operador usado para concatenar duas strings em Python? ', '*', '%', '+', '&', '3', 'python'),
	('Qual dos seguintes métodos é usado para remover um elemento de um conjunto em Python? ', 'discard()', 'remove()', 'delete()', 'pop()', '1', 'python'),
	('Qual é a saída do seguinte código Python? print(2 ** 3)', '5', '8', '16', '23', '2', 'python'),
	('Qual dos seguintes módulos é usado para trabalhar com arquivos em Python? ', 'sys', 'os', 'math', 'time', '2', 'python'),
	('Qual é a função usada para ler entrada do usuário em Python?', 'input()', 'get()', 'read()', 'scan()', '1', 'python'),
	('Qual método é usado para ordenar uma lista em Python?', 'sort()', 'sorted()', 'order()', 'arrange() ', '1', 'python'),
	('"Qual é a função do operador ""=="" em Python? "', 'Verificar se dois valores são idênticos', 'Realizar uma atribuição de valor', 'Incrementar uma variável', 'Multiplicar dois números', '1', 'python'),
	('Qual é a forma correta de declarar uma variável em Python?', 'nome_variavel = valor', 'var nome_variavel = valor ', 'let nome_variavel = valor ', 'const nome_variavel = valor', '1', 'python'),
	('Qual é a estrutura de controle utilizada para repetir um bloco de código enquanto uma condição for verdadeira em Python?', 'for loop', 'if statement', 'while loop', 'switch case', '3', 'python'),
	('Qual é o método utilizado para converter uma string em letras minúsculas em Python?', 'lower()', 'capitalize() ', 'upper()', 'swapcase()', '1', 'python'),
	('Qual é o tipo de dado utilizado para representar números inteiros em Python? ', 'int', 'float', 'str', 'bool', '1', 'python'),
	('Em Python, qual é o método utilizado para verificar se uma determinada chave existe em um dicionário? ', 'find()', 'contains() ', 'exists() ', 'in', '4', 'python'),
	('Qual é a função utilizada para arredondar um número para o inteiro mais próximo em Python? A) round() ', 'round()', 'ceil()', 'floor() ', 'abs()', '1', 'python'),
	('Em Python, qual é o método utilizado para dividir uma string em substrings com base em um caractere de separação? ', 'split() ', 'join() ', 'replace()', 'slice()', '1', 'python'),
	('Qual é o método utilizado para adicionar um elemento no final de uma lista em Python? ', 'insert() ', 'append() ', 'extend() ', 'push()', '2', 'python'),
	('Em Python, qual é o operador lógico utilizado para verificar se duas condições são verdadeiras? ', '&& ', '||', 'and', '!', '3', 'python'),
	('Qual é o tipo de dado utilizado para representar uma sequência imutável de elementos em Python? ', 'list', 'dictionary', 'set', 'tuple', '4', 'python'),
	('Qual é o método utilizado para obter o valor absoluto de um número em Python? ', 'round()', 'abs() ', 'sqrt()', 'pow()', '2', 'python'),
	('Em Python, qual é a função utilizada para encontrar o valor máximo em uma lista? ', 'min()', 'sort()', 'sum()', 'max()', '4', 'python'),
	('Qual é a estrutura de controle utilizada para executar um bloco de código caso uma condição seja verdadeira e outro bloco caso seja falsa em Python?', 'if-else statement', 'while loop', 'for loop', 'switch case', '1', 'python'),
	('Em Python, qual é o método utilizado para converter um número em uma string? ', 'int()', 'str()', 'float()', 'convert()', '2', 'python'),
	('Qual é o operador utilizado para realizar a concatenação de strings em Python?', '/', '-', '+', '*', '3', 'python'),
	('Qual é o modificador de acesso utilizado para tornar um atributo ou método visível apenas dentro da mesma classe em Java? ', 'private', 'protected', 'public', 'default', '1', 'java'),
	('Em Java, qual é o tipo de dado utilizado para representar números de ponto flutuante de precisão dupla? ', 'int', 'float', 'double', 'decimal', '3', 'java'),
	('Qual é a palavra-chave utilizada para criar uma instância de uma classe em Java? ', 'new', 'this', 'class', 'instance', '1', 'java'),
	('Em Java, qual é o operador utilizado para realizar uma comparação de igualdade entre dois valores? ', '=', '==', '!=', '===', '2', 'java'),
	('Qual é a estrutura de controle utilizada para executar um bloco de código repetidamente enquanto uma condição for verdadeira em Java? ', 'for loop', 'if statement', 'while loop', 'switch case', '3', 'java'),
	('Em Java, qual é o modificador de acesso utilizado para tornar um atributo ou método visível para todas as classes dentro do mesmo pacote? ', 'private', 'protected', 'public', 'default', '4', 'java'),
	('Qual é o método utilizado para obter o tamanho de um array em Java?', 'count()', 'sort()', 'length() ', 'size()', '3', 'java'),
	('Em Java, qual é o método utilizado para ler a entrada do usuário? ', 'input()', 'print() ', 'read() ', 'Scanner.nextLine()', '4', 'java'),
	('Qual é o operador utilizado para realizar uma multiplicação entre dois valores em Java? ', '+', '-', '*', '/', '3', 'java'),
	('Em Java, qual é a palavra-chave utilizada para definir uma classe pai de outra classe? ', 'super', 'parent', 'this', 'extends', '4', 'java'),
	('Em Java, qual é o modificador de acesso utilizado para tornar um atributo ou método visível para todas as classes, independentemente do pacote em que se encontram? ', 'private', 'protected', 'public ', 'default', '3', 'java'),
	('Qual é o método utilizado para converter uma string em um número inteiro em Java? ', 'convertToInt()', 'parseInt() ', 'toInt() ', 'toInteger()', '2', 'java'),
	('Em Java, qual é o tipo de dado utilizado para representar valores booleanos? ', 'boolean', 'int', 'double', 'char', '1', 'java'),
	('Qual é a estrutura de controle utilizada para executar um bloco de código para um conjunto finito de valores em Java? ', 'for loop', 'while loop', 'do-while loop', 'switch case', '1', 'java'),
	('Em Java, qual é a classe base de todas as classes do pacote java.lang? ', 'Object', 'String', 'System', 'Math', '1', 'java'),
	('Qual é o método utilizado para verificar se um objeto é uma instância de uma determinada classe em Java? ', 'isInstance()', 'instanceOf() ', 'isClass() ', 'getClass()', '2', 'java'),
	('Em Java, qual é o operador utilizado para realizar uma concatenação de strings? ', '+', '-', '*', '/', '1', 'java'),
	('Qual é o método utilizado para remover um elemento de um ArrayList em Java? ', 'remove() ', 'delete()', 'erase() ', 'pop()', '1', 'java'),
	('Em Java, qual é a palavra-chave utilizada para indicar que um método não retornará nenhum valor? ', 'void', 'null', 'empty', 'none', '1', 'java'),
	('Qual é o método utilizado para imprimir uma mensagem no console em Java? ', 'print() ', 'println() ', 'log()', 'write()', '2', 'java'),
	('Qual é o comando utilizado para criar um novo banco de dados no MySQL?', 'CREATE', 'INSERT', 'UPDATE', 'SELECT', '1', 'sql'),
	('Qual é o comando utilizado para selecionar todos os registros de uma tabela no MySQL? ', 'SELECT * ', 'SELECT ALL', 'SELECT ROWS', 'SELECT TABLE', '1', 'sql'),
	('Qual é o operador usado para combinar múltiplas condições em uma cláusula WHERE no MySQL? ', 'OR', 'XOR', 'NOT', 'AND', '4', 'sql'),
	('Qual é o comando usado para inserir dados em uma tabela no MySQL?', 'INSERT INTO ', 'UPDATE', 'ADD INTO', 'SET VALUES', '1', 'sql'),
	('Qual é o comando utilizado para atualizar dados em uma tabela no MySQL? ', 'ALTER TABLE', 'UPDATE', 'MODIFY TABLE', 'REPLACE INTO', '2', 'sql'),
	('Qual é o comando utilizado para excluir uma tabela no MySQL? ', 'DELETE', 'TRUNCATE', 'REMOVE', 'DROP', '4', 'sql'),
	('Qual é o tipo de dados usado para armazenar valores monetários no MySQL?', 'INTEGER', 'CHAR', 'DECIMAL', 'VARCHAR', '3', 'sql'),
	('Qual é o comando utilizado para renomear uma tabela no MySQL? ', 'RENAME TABLE ', 'ALTER TABLE ', 'MODIFY TABLE', 'UPDATE TABLE', '1', 'sql'),
	('Qual é o operador utilizado para ordenar os resultados de uma consulta em ordem decrescente no MySQL? ', 'DESC', 'ASC', 'ORDER BY DESC', 'SORT DESC', '1', 'sql'),
	('Qual é o comando utilizado para criar uma chave primária em uma tabela no MySQL? ', 'PRIMARY KEY', 'KEY', 'INDEX', 'UNIQUE', '1', 'sql'),
	('Qual é o comando utilizado para criar uma tabela no MySQL? ', 'INSERT', 'CREATE TABLE', 'UPDATE', 'SELECT', '2', 'sql'),
	('Qual é o comando usado para adicionar uma nova coluna a uma tabela existente no MySQL? ', 'ALTER TABLE', 'UPDATE TABLE', 'ADD COLUMN', 'MODIFY TABLE', '1', 'sql'),
	('Qual é o operador usado para buscar um padrão específico em uma consulta SELECT no MySQL? ', 'LIKE', 'WHERE', 'MATCH', 'IN', '1', 'sql'),
	('Qual é o comando utilizado para realizar uma junção (join) entre duas ou mais tabelas no MySQL? ', 'MERGE', 'UNION', 'JOIN', 'CONCAT', '2', 'sql'),
	('Qual é o comando usado para fazer uma cópia de segurança (backup) de um banco de dados no MySQL?', 'BACKUP DATABASE', 'SAVE DATABASE', 'EXPORT DATABASE', 'mysqldump', '4', 'sql'),
	('Qual é o tipo de dados usado para armazenar valores de data e hora no MySQL? ', 'DATE', 'TIME', 'DATETIME', 'TIMESTAMP', '3', 'sql'),
	('Qual é o comando utilizado para limitar o número de registros retornados por uma consulta SELECT no MySQL? ', 'SET LIMIT', 'TOP', 'LIMIT', 'COUNT', '3', 'sql'),
	('Qual é o operador utilizado para verificar se um valor está dentro de uma lista de valores no MySQL? ', 'BETWEEN', 'IN', 'EXISTS', 'IS NULL', '2', 'sql'),
	('Qual é o comando utilizado para conceder privilégios a um usuário no MySQL? ', 'GRANT', 'ALLOW', 'SET PRIVILEGES', 'GIVE', '1', 'sql'),
	('Qual é o comando utilizado para revogar privilégios de um usuário no MySQL? ', 'REVOKE', 'DENY', 'REMOVE PRIVILEGES', 'TAKE AWAY', '1', 'sql');

SELECT * FROM perguntas;

drop table perguntas;